### ISSUE TITLE
Allow to adjust/increase of the dismiss timer

### ISSUE THREAD

**Issue by inteist** [uias/CocoaBar#17]
In case of multiple calls for snackbar, the default behavior is for the bars to stack up. We do not like that behavior and it works better for our use case if we only have the snackbar reflect the last action. Everything works except one small thing. The problem is if say we have 2 actions with an interval of 1 seconds and say the snackbar disappears after 2 seconds, when we update the snackbar after the second action the timer does not get "updated" and the snackbar disappears after 1 second after the second action as opposed to 2 seconds as it should be. 

Can you please whether tell me how I can use the library in such a use case or perhaps you can update the library and expose a method to "reset" the timer (basically prolonging its display) in some way.

Thanks.

**Comment by msaps** [comment]
Hi, 

This is now available in [0.1.7](https://github.com/MerrickSapsford/CocoaBar/releases/tag/0.1.7)

You can reset the active display timer by using the `resetDisplayTimer` functions that are now available in `CocoaBar`. They do the following:
- `resetDisplayTimer()` - Reset the display timer with the currently active duration.
- `resetDisplayTimer(duration: DisplayDuration)` - Reset the display timer with a specified new `DisplayDuration` enum value.
- `resetDisplayTimer(duration: Double)` - Reset the display timer with a specified duration.

Cheers,
Merrick

**Comment by inteist** [comment]
Uuuu-huuu! Thanks a lot for such a prompt implement!
