### ISSUE TITLE
Swift 3 CocoaPod

### ISSUE THREAD

**Issue by JRG-Developer** [uias/CocoaBar#20]
I see a commit on September 9th with message "use conversion tool," so it looks like you've started the process of converting to Swift 3.

However, the `Example` project still prompts to convert this, so it looks like there's a bit to be done still.

Do you have plans for Swift 3 release, in particular new CocoaPod version?

If you're too bogged down, will you accept/review PR for such? I'm happy to help here as I'm going to be needing it soon and would prefer to get changes into upstream if possible. 😄

**Comment by msaps** [comment]
Hi,

Meant to finish this off with the GM release but never got round to it! 

I've added the bare bones update to Swift 3 and done a quick check to make sure everything is working, and released a new version: [0.2.0-beta1](https://github.com/MerrickSapsford/CocoaBar/releases/tag/0.2.0-beta1). 

I plan on finishing this off next week, so a stable 0.2.0 release should be available then. Nothing major will change, just need to check the access controls and clean things up a bit 😄  

Feel free to contribute if you can think of anything though!

**Comment by msaps** [comment]
[0.2.0-beta 2](https://github.com/MerrickSapsford/CocoaBar/releases/tag/0.2.0-beta2) is now available. 

Just some slight refactoring and access control updates.

**Comment by msaps** [comment]
[0.2.0](https://github.com/MerrickSapsford/CocoaBar/releases/tag/0.2.0) is now available, with Swift 3 support and a few other minor enhancements. 

Enjoy 😄

**Comment by JRG-Developer** [comment]
Awesome. Thanks! 👍
